# Generated by Django 5.2.17 on 2026-09-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('thumbnail_url', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=200)),
                ('platform', models.CharField(choices=[('coursera', 'Coursera'), ('edx', 'edX'), ('youtube', 'YouTube'), ('freecodecamp', 'freeCodeCamp'), ('mit_ocw', 'MIT OpenCourseWare'), ('nptel', 'NPTEL'), ('khan_academy', 'Khan Academy'), ('cs50', 'CS50'), ('the_odin_project', 'The Odin Project'), ('unacademy', 'Unacademy'), ('physics_wallah', 'Physics Wallah'), ('other', 'Other')], default='other', max_length=30)),
                ('category', models.CharField(choices=[('python', 'Python'), ('web-development', 'Web Development'), ('data-analytics', 'Data Analytics'), ('ai-machine-learning', 'AI & Machine Learning'), ('ui-ux-design', 'UI/UX Design'), ('digital-marketing', 'Digital Marketing')], max_length=50)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('youtube', 'YouTube'), ('video', 'Video'), ('certificate', 'Certificate'), ('tutorial', 'Tutorial'), ('playlist', 'Playlist')], default='course', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All levels')], default='', max_length=20)),
                ('duration_text', models.CharField(blank=True, default='', max_length=100)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'), models.Index(fields=['is_free'], name='resources_r_is_free_94bf3d_idx'), models.Index(fields=['platform'], name='resources_r_platfor_a129d9_idx'), models.Index(fields=['rating'], name='resources_r_rating_f4fc68_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
